function [] = PlotAllAnglesInConfigurationSpaceForLoopNumber( LoopNumber )
%PlotAllAnglesInConfigurationSpace returns 3 plots containing the cubic
%splines for the three joints for 1000 trials. Input LoopNumber (1-100).

% Check number of inputs.
if nargin > 1
    error('myfuns:PlotXY:TooManyInputs', ...
        'requires 1 input');
else if nargin == 0
        error('myfuns:PlotXY:NotEnoughInputs', ...
            'requires 1 input');
    end
end

FileName = ['.\LoopNumberTrials\LoopNumber' num2str(LoopNumber) '.mat'];
load(FileName,'Angle1SplineStructures','Angle2SplineStructures',...
            'Angle3SplineStructures','Time');
        
Angle1 = zeros(1000,length(Time));
Angle2 = zeros(1000,length(Time));
Angle3 = zeros(1000,length(Time));

for i = 1:1000
    Angle1(i,:) = ppval(Angle1SplineStructures(i),Time);
    Angle2(i,:) = ppval(Angle2SplineStructures(i),Time);
    Angle3(i,:) = ppval(Angle3SplineStructures(i),Time);
end

figure;
    plot(Time, Angle1(:,:));
    title('\theta_{1} Physiologically Feasible Splines',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    xlabel('Time (s)',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    ylabel('Shoulder Joint Angle, \theta_{1} (radians)',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    set(gca,'TickDir',      'out',...
        'TickLength',   [0.02 0.02],...
        'XColor',       [.3 .3 .3],...
        'YColor',       [.3 .3 .3],...
        'LineWidth',        1,...
        'box',          'off');
    set(gcf,'PaperPositionMode','auto');

figure;
    plot(Time, Angle2(:,:));
    title('\theta_{2} Physiologically Feasible Splines',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    xlabel('Time (s)',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    ylabel('Elbow Joint Angle, \theta_{2} (radians)',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    set(gca,'TickDir',      'out',...
        'TickLength',   [0.02 0.02],...
        'XColor',       [.3 .3 .3],...
        'YColor',       [.3 .3 .3],...
        'LineWidth',        1,...
        'box',          'off');
    set(gcf,'PaperPositionMode','auto');

figure;
    plot(Time, Angle3(:,:));
    title('\theta_{3} Physiologically Feasible Splines',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    xlabel('Time (s)',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    ylabel('Wrist Joint Angle, \theta_{3} (radians)',...
        'FontName',     'AvantGarde',...
        'FontSize',     14,...
        'Color',        [.3 .3 .3]);
    set(gca,'TickDir',      'out',...
        'TickLength',   [0.02 0.02],...
        'XColor',       [.3 .3 .3],...
        'YColor',       [.3 .3 .3],...
        'LineWidth',        1,...
        'box',          'off');
    set(gcf,'PaperPositionMode','auto');
end

