NumberOfBins = 20;
Count = HistogramCount(NumberOfBins);

figure;
    Histogram = pcolor(Count);
    set(Histogram,...
        'EdgeColor',    'none');
    CustomColorMap = [ones(101,1) sort(0:0.01:1,'descend')'  sort(0:0.01:1,'descend')'];
    colormap(CustomColorMap);
%     colormap jet;
    set(gca,'FontName','AvantGarde');
    set(gca,...
        'TickDir',      'out',...
        'TickLength',   [0.02 0.02],...
        'XTick',        1:4:NumberOfBins+1,...
        'YTick',        1:4:NumberOfBins+1);
    set(gca,...
        'XTickLabel',   {'0',...
                        '100',...
                        '200',...
                        '300',...
                        '400',...
                        '500'},...
        'YTickLabel',   {'0',...
                        '100',...
                        '200',...
                        '300',...
                        '400',...
                        '500'},...
        'XColor',       [.3 .3 .3],...
        'YColor',       [.3 .3 .3],...
        'Box',          'off',...
        'YGrid',        'off',...
        'XGrid',        'off');
    axis equal;
    axis tight;
    xlabel('Sum of Maximum Eccentric Velocities Squared',...
        'Color',        [.3 .3 .3],...
        'FontName',     'AvantGarde',...
        'FontSize',     14);
    ylabel('Sum of Maximum Concentric Velocities Squared',...
        'Color',        [.3 .3 .3],...
        'FontName',     'AvantGarde',...
        'FontSize',     14);
    set(gcf,'PaperPositionMode','auto');
    c = colorbar();
    set(c,...
        'box',          'off',...
        'TickDir',      'out',...
        'TickLength',   [0.02 0.02],...
        'YColor',       [.3 .3 .3],...
        'FontName',     'AvantGarde',...
        'LineWidth',    1);
    set(get(c,'YLabel'),...
        'String',       'Number Of Valid Shots',...
        'Color',        [.3 .3 .3],...
        'FontName',     'AvantGarde',...
        'FontSize',     14);

    
    